/**
 * LoginForm.js
 *
 * This is input component of the login module. It handles the input by using
 * function props passed down from the parent component.
 */
import React from 'react';
import PropTypes from 'prop-types';

import '../Components.css';

export class LoginForm extends React.Component {
  /**
   * LoginForm constructor
   * -binds methods handleUsernameChange and handlePasswordChange
   *
   * @param: to pass any props to React components
   */
  constructor(props) {
    super(props);

    this.handleUsernameChange = this.handleUsernameChange.bind(this);
    this.handlePasswordChange = this.handlePasswordChange.bind(this);
  } // end constructor


  /**
   * handleUsernameChange:
   * This method calls the state-modifying method of the parent component using
   * when an event is generated by the username input being changed.
   */
  handleUsernameChange(e) {
    this.props.onUsernameChange(e.target.value);
  } // end handleUsernameChange()


  /**
   * handleUsernameChange:
   * This method calls the state-modifying method of the parent component using
   * when an event is generated by the username input being changed.
   */
  handlePasswordChange(e) {
    this.props.onPasswordChange(e.target.value);
  } // end handlePasswordChange()


  /**
   * render:
   * Required method of React components to create JFX element.
   */
  render() {
    return (
      <div className="login-form">
        <div>
          <span className="login-label">username</span>
          <input
            className="login-field"
            type="text"
            onChange={this.handleUsernameChange}
          />
        </div>
        <div>
          <span className="login-label">password</span>
          <input
            className="login-field"
            type="password"
            onChange={this.handlePasswordChange}
          />
        </div>
      </div>
    );
  } // end render()
} // end class LoginField


/**
 * props:
 *
 * Required:
 * onUsernameChange - username state modifying method of the parent component
 * onPasswordChange - password state modifying method of the parent component
 */
LoginForm.propTypes = {
  onUsernameChange: PropTypes.func.isRequired,
  onPasswordChange: PropTypes.func.isRequired,
};

export default LoginForm;
